name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
    
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  ECR_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/proj/dnd-13th-9-backend
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build & Test
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ECR-CICD-ROLE
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/ECR-CICD-ROLE
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ vars.EC2_INSTANCE_ID }} \
            --document-name AWS-RunShellScript \
            --comment "Deploy myproj" \
            --parameters commands='[
              "aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com",
              "docker pull ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}",
              "docker stop myapp || true",
              "docker rm myapp || true",
              "docker run -d --name myapp --restart always -p 8080:8080 ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}"
            ]' \
            --output text
